
services:
  api:
    build: .
    container_name: logflow-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongodb
      - redis
    networks:
      - logflow-net

  mongodb:
    image: mongo:6
    container_name: logflow-mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - logflow-net

  redis:
    image: redis:7-alpine
    container_name: logflow-redis
    restart: unless-stopped
    networks:
      - logflow-net

  nginx:
    image: nginx:alpine
    container_name: logflow-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - logflow-net

  prometheus:
    image: prom/prometheus:latest
    container_name: logflow-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - logflow-net

  localstack:
    image: localstack/localstack:3.0.0
    container_name: logflow-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,iam
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - logflow-net
    volumes:
      - localstack-data:/var/lib/localstack
    depends_on:
      - api
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: logflow-client
    networks:
      - logflow-net
    
networks:
  logflow-net:
    driver: bridge

volumes:
  mongo-data:
  localstack-data:
