apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: 866972254535.dkr.ecr.us-east-1.amazonaws.com/logflow-alert-service:latest
          envFrom:
            - configMapRef:
                name: logflow-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"