apiVersion: batch/v1
kind: CronJob
metadata:
  name: logflow-cleanup
  namespace: default
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              image: 866972254535.dkr.ecr.us-east-1.amazonaws.com/logflow-api:latest
              command: ["node", "src/cleanup.js"]
              envFrom:
                - configMapRef:
                    name: logflow-config
          restartPolicy: OnFailure

          