apiVersion: v1
kind: Service
metadata:
  name: logflow-service
  namespace: default
spec:
  selector:
    app: logflow-api
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001