apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: 866972254535.dkr.ecr.us-east-1.amazonaws.com/logflow-simulator:latest
          envFrom:
            - configMapRef:
                name: logflow-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"